import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function Navbar() {
  return (
    <nav className="bg-gray-400 text-black p-4 w-full flex items-center justify-between">
      <div>Gallery</div>
      <div>Sign in</div>
    </nav>
  );
};
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Navbar/>  
        {children}
      </body>
    </html>
  );
}
